# Make sure to check the documentation at https://goreleaser.com
project_name: taikun
before:
  hooks:
    - go mod tidy -compat=1.21
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - id: 3.0.0-alpha.2
    name_template: >-
      {{- .ProjectName }}_
      {{- .Tag }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
#  - replacements:
#      darwin: Darwin
#      linux: Linux
#      windows: Windows
#      386: i386
#      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
release:
  name_template: "Taikun CLI {{.Version}}"
  prerelease: auto
changelog:
  use: github-native
