name: Scheduled Tests
on:
  workflow_dispatch:
  schedule:
    - cron: 0 2 * * 5

jobs:
  call-workflow-1-in-local-repo:
    uses: ./tests_reusable.yml
    with:
      branch: dev # Scheduled tests always run from dev branch
    secrets:
      # Run against dev taikun endpoint
      USE_API_HOST: ${{ secrets.TAIKUN_API_HOST }}
      USE_EMAIL: ${{ secrets.TAIKUN_EMAIL }}
      USE_PASSWORD: ${{ secrets.TAIKUN_PASSWORD }}
      inherit: true
