name: Tests
on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  build:
    name: Build
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          go build -v .

  golangci:
    name: Lint
    runs-on: self-hosted
    needs: build
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint (golangci-lint)
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  test:
    name: Test
    runs-on: self-hosted
    needs: golangci
    timeout-minutes: 60
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install shellspec
        run: |
          set -o pipefail
          curl -fsSL https://git.io/shellspec | sh -s 0.28.1 -y

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          export GOPATH=$(go env GOPATH)
          export PATH=$PATH:$GOPATH/bin
          make install

      - name: Run shellspec
        env:
          TAIKUN_EMAIL: ${{ secrets.TAIKUN_EMAIL }}
          TAIKUN_PASSWORD: ${{ secrets.TAIKUN_PASSWORD }}
          TAIKUN_API_HOST: ${{ secrets.TAIKUN_API_HOST }}
        run: |
          shellspec
