name: Tests
on:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    uses: ./.github/workflows/tests_reusable.yml
    with:
      branch: ${{ github.ref }} # Run on the branch of this PR
      endpoint: "dev"           # Run against dev taikun endpoint
    secrets: inherit