name: "🆕 Tests"
on:
  workflow_dispatch:
  # Trigger on all pull requests made to dev repository
  pull_request:
    branches:
      - dev

jobs:
  tests:
    uses: ./.github/workflows/tests_reusable.yml
    with:
      branch: ${{ github.ref }} # Run on the branch of this PR
      endpoint: "dev"           # Run against dev taikun endpoint
    secrets: inherit