name: Tests
on:
  pull_request:
  workflow_dispatch:

jobs:
  call-workflow-1-in-local-repo:
    uses: ./tests_reusable.yml
    with:
      branch: ${{ github.ref }} # Run on the branch of this PR
    secrets:
      # Run against dev taikun endpoint
      USE_API_HOST: ${{ secrets.TAIKUN_API_HOST }}
      USE_EMAIL: ${{ secrets.TAIKUN_EMAIL }}
      USE_PASSWORD: ${{ secrets.TAIKUN_PASSWORD }}
      inherit: true
