name: Tests
on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  build:
    name: Build
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          go build -v .

  golangci:
    name: Lint
    runs-on: self-hosted
    needs: build
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint (golangci-lint)
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
