name: "📚 Update command tree"
on:
  push:
    branches:
      - 'main'
      - 'staging'
      - 'dev'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'NOTICE'
      - 'Dockerfile'
      - 'GNUmakefile'
      - 'go.mod'
      - 'go.sum'
      - 'api/**'
      - 'apiconfig/**'
      - 'config/**'
      - 'utils/**'
      - '.github/CONTRIBUTING.md'

env:
  GO_VERSION: '1.20'

jobs:
  update_command_tree:
    name: Update command tree
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build command tree
        id: check
        run: |
          ./scripts/docs/build_command_tree.sh
        continue-on-error: true

      - name: Setup Git
        if: steps.check.outcome == 'success'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Commit
        if: steps.check.outcome == 'success'
        run: |
          git add .
          git commit -m "docs: update command tree"

      - name: Push
        if: steps.check.outcome == 'success'
        run: git push
